from NLP_Processer import NLP_Processer 
import json

if __name__ == "__main__":
    val = input("Welcome to manual test platform\nEnter sentense ")
    val = "University of Minnesota. Driven to Discover.US levels of clinic visits for influenza-like illness (ILI), after falling for 3 straight weeks, rose slightly last week, but the increase might be related to concerns over COVID-19, according to the latest FluView report from the Centers for Disease Control and Prevention (CDC), and the flu season continues to take a toll on children.The CDC confirmed eight new flu-associated pediatric deaths during the week ending Mar 7.\"Pneumonia and influenza mortality has been low, but 144 influenza-associated deaths in children have been reported so far this season,\" the CDC said. \"This number is higher for the same time period than in every season since reporting began in 2004-05, except for the 2009 pandemic.\"The overall cumulative flu-associated hospitalization rate increased to 61.6 per 100,000 population, which is higher than all recent seasons at this time of year except for 2017-18. Hospitalization rates in children 0 to 4 years (88.9 per 100,000 population) and adults 18 to 49 years (32.8 per 100,000 population) are now the highest the CDC has on record.All regions reported a percentage of outpatient visits for ILI above their region-specific baselines. Nationally, the rate of outpatient visits for ILI increased from 5.1% to 5.2%—still well above the national baseline of 2.4%.High ILI activity was reported in New York City, Puerto Rico, and 41 states, up from 40 the previous week. The number of regions reporting widespread or regional flu activity fell from 51 to 50. The CDC also noted that the largest increases in ILI activity occurred in areas of the country where the pandemic coronavirus disease COVID-19 is most prevalent.\"More people may be seeking care for respiratory illness than usual at this time,\" the CDC said.Testing by public health laboratories shows that 55.2% of the circulating viruses tested since Sep 29, 2019, are influenza A, and 44.8% are influenza B. The most common influenza A viruses are 2009 H1N1 (92.2%), while 98.4% of influenza B samples belon"
    nlp_processer = NLP_Processer()
    nlp_processer.set_publication_date("2020-02-03 12:12:12")
    json_file = nlp_processer.make_reports(val)[0]
    # print(json_file)
    print(nlp_processer.get_keyword_frequency())
    print(nlp_processer.get_keyword_list())